[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'cp node_modules/pdfjs-dist/build/pdf.worker.min.mjs public/pdf.worker.min.js',
  'npm run build',
  'npm install -g serve'
]

[start]
cmd = 'serve -s build -l $PORT'