[phases.setup]
nixPkgs = ['python3', 'gcc', 'postgresql']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p uploads']

[variables]
PYTHONPATH = '/app/backend'

[start]
cmd = 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT'