[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "pip install -r requirements.txt"
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[services.variables]
PYTHONPATH = "/app"
PORT = "8000"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[services.variables]
PORT = "3000"
NODE_ENV = "production"