# Railway Configuration for Ulrich AI LMS

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
source = "backend"

[services.env]
# These will be set in Railway dashboard
# Listed here for reference only
# APP_NAME = "Ulrich AI"
# APP_VERSION = "0.1.0"
# ENVIRONMENT = "production"

# Frontend Service
[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
